version: '2'
services:
    hdfs-name:
        image: quay.io/geodocker/hdfs:latest
        command: name
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
        ports:
          - 50070:50070
        # volumes:
        #   - ./service/geotrellis/data/chatta-demo:/data/hdfs
    hdfs-data:
        image: quay.io/geodocker/hdfs:latest
        command: data
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
        depends_on:
          - hdfs-name
        # volumes:
        #  - ./service/geotrellis/data/chatta-demo:/data/hdfs
    zookeeper:
        image: quay.io/geodocker/zookeeper:latest
        ports:
          - 2181:2181
        # volumes:
        # - ./service/geotrellis/data/chatta-demo:/data/hdfs
    accumulo-master:
      image: quay.io/geodocker/accumulo:latest
      command: master --auto-init
      environment:
        HADOOP_MASTER_ADDRESS: hdfs-name
        ZOOKEEPERS: zookeeper
        ACCUMULO_PASSWORD: GisPwd
      depends_on:
        - zookeeper
        - accumulo-monitor
        - accumulo-tserver
    accumulo-monitor:
        image: quay.io/geodocker/accumulo:latest
        command: monitor
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
          ZOOKEEPERS: zookeeper
        ports:
          - 50095:50095
        depends_on:
          - zookeeper
    accumulo-tserver:
        image: quay.io/geodocker/accumulo:latest
        command: tserver
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
          ZOOKEEPERS: zookeeper
        depends_on:
          - zookeeper
    spark-master:
        image: quay.io/geodocker/spark:latest
        working_dir: /data/geotrellis
        command:
          - ./sbt
          - runMain geotrellis.chatta.Main
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
        ports:
          - 4040:4040
          - 8080:8080
          - 8777:8777
        depends_on:
          - hdfs-data
          - accumulo-master
        volumes:
          - "${HOME}/.ivy2:/root/.ivy2"
          - "${HOME}/.m2:/root/.m2"
          - "${HOME}/.sbt:/root/.sbt"
          - "./service/geotrellis/:/data/geotrellis"
          - "./service/geotrellis/data:/data"
          - "./geodocker/application.geodocker.conf:/data/geotrellis/src/resources/application.conf"          
          - "./geodocker/backend-profiles.geodocker.json:/data/geotrellis/conf/backend-profiles.json"
          - "./service/static:/static"
    spark-worker:
        image: quay.io/geodocker/spark:latest
        command: worker
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
          SPARK_MASTER: spark-master
        depends_on:
          - spark-master